### Creating and manipulating  arrays


### Problem 1
We are going to explore various ways to create an array object of various data dtypes.

1. Create a vector starting from 2, 20 inclusive in unit steps with `np.arange`. Example: `np.arange(2,4)` outputs array([2,3])

2. Create the same array object using `np.array` and a `list`

3. Every **`numpy.ndarray`** has a data dtype object. This data type indicates whether the elements in an array is `string`, `integer`,`float`, `boolean` or user defined data type. Now use the attribute `dtype` to querry the data types created in  _question 2._

4. One can specify the data type during creation of an array like so: np.array([...], __dtype__ = my_dtype). Example  np.array([1,2,4], dtype = np.float32). Now create a boolean vector of length 10. Don't forget to specify the data dtype. [Hint: see [dtypes](https://docs.scipy.org/doc/numpy-dev/user/basics.types.html)]

5. 
    1. Using __linspace__ create a vector: start = 3, end = 5. the length out should be 200
    2. Change the shape of the vector to 2 X 50 X 2.
    3. what is the dimension of the vector in  _question 5.C_


### Solution for problem 1

In [2]:
#start by importing numpy as np
import numpy as np
from __future__ import print_function

In [11]:
#1. using np.arange, step is 1 by default
x = np.arange(2, 21)
print('x = ', x)
#2. using np.array
y = np.array(range(2,21), dtype = np.float_)
print('y = ', y)

#3. querring data dtypes
print(x.dtype)
print(y.dtype)

#4. note np.bool_ is the same as python's 'bool' object
_bool = np.array([0,1]*5, dtype = np.bool_)
print(_bool)

#5.A
xx = np.linspace(3, 5, 200)
print('xx = ', xx)
#5.B
xx = xx.reshape((2,50,2))
print('xx = ', xx)

#5.C
print('Dimension of xx is ', str(xx.ndim))


x =  [ 2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
y =  [  2.   3.   4.   5.   6.   7.   8.   9.  10.  11.  12.  13.  14.  15.  16.
  17.  18.  19.  20.]
int64
float64
[False  True False  True False  True False  True False  True]
xx =  [ 3.          3.01005025  3.0201005   3.03015075  3.04020101  3.05025126
  3.06030151  3.07035176  3.08040201  3.09045226  3.10050251  3.11055276
  3.12060302  3.13065327  3.14070352  3.15075377  3.16080402  3.17085427
  3.18090452  3.19095477  3.20100503  3.21105528  3.22110553  3.23115578
  3.24120603  3.25125628  3.26130653  3.27135678  3.28140704  3.29145729
  3.30150754  3.31155779  3.32160804  3.33165829  3.34170854  3.35175879
  3.36180905  3.3718593   3.38190955  3.3919598   3.40201005  3.4120603
  3.42211055  3.4321608   3.44221106  3.45226131  3.46231156  3.47236181
  3.48241206  3.49246231  3.50251256  3.51256281  3.52261307  3.53266332
  3.54271357  3.55276382  3.56281407  3.57286432  3.58291457  3.59296482
  3.60301508  3.613065

### Problem 2
Numpy as a lot of factory function for creating numpy arrays. You have already seen some of them like: `np.linspace` and `np.arange`. Let explore the a lot more. Numpy has a submodule called the random. It can be accessed by **importing** them like so: `from numpy import random`. With this module you can sample from nearly all the theoritical distributions out there. Let take it for a spin:

1. Create a 5X5 matrix of standard normal. [Hint: A couple of options. random.normal, random.standard_normal]. Make sure you specify the __shape__ of the matrix.

2. Scale the element in the matrix by a factor of 10. Then take the floor of the results.

3. Set every negative element in the matrix to zero. [Hint: using boolean indexing like so: A[A < 0]]

4. Using `np.nonzero` find the locations of the nonzero elements. 

5. Use the indices to fetch the nonzero elements from the matrix. You get a 1-D array of nonzero elements of the matrix

6. Now create matrix of ones of size 5 X 5. Fill in the Matrix of ones by the nonzero elements of _question 5_
[Hint: np.ones]

7. Repeat _question 6_ but use a matrix of **zeros** inplace of ones. 

8. Investigate the the functions `np.eye` and `np.identity`. What are their difference and similarities

9. Repeat _question 6_ but use the identity matrix inplace of ones.

10. What is the difference between `np.arange` and `np.linspace`

### Solution for problem 2

In [23]:
from numpy import random
random.seed(1258)

#1.
rand_normal = random.standard_normal((5,5))
print('Standard normal = ',rand_normal)

#2. 
rand_normal = np.floor(10*rand_normal)
print('scaled stardard normal = ', rand_normal)
#3.
rand_normal[rand_normal < 0] = 0
print(rand_normal)

#4. 
i, j = np.nonzero(rand_normal)
print('x coordinates of nonzero elements = ', i)
print('y coordinates of nonzero elements = ', j)

#5. 
nonzero = rand_normal[i,j]
print(nonzero)

#6. 
ones = np.ones((5,5))
ones[i,j] = rand_normal[i,j]
print('ones filled with nonzero element from rand_normal = ',ones, sep = '\n')

#7. 
zeros = np.zeros((5,5))
zeros[i,j] = rand_normal[i,j]
print('Zeros filled with nonzero element from rand_normal = ', zeros, sep = '\n')

Standard normal =  [[ 0.80336542 -1.01396645 -2.09267517  0.84862408 -0.15797219]
 [-0.37300791  0.06279288 -0.17724302  0.03377207 -0.78157072]
 [-0.96593116 -0.73662257 -1.1441852  -3.59981609 -1.45474597]
 [ 1.81398599  0.00548929 -0.73692779  2.32898432 -1.5328748 ]
 [ 0.86973466  0.34816644 -1.48106976 -1.0178757  -1.13974695]]
scaled stardard normal =  [[  8. -11. -21.   8.  -2.]
 [ -4.   0.  -2.   0.  -8.]
 [-10.  -8. -12. -36. -15.]
 [ 18.   0.  -8.  23. -16.]
 [  8.   3. -15. -11. -12.]]
[[  8.   0.   0.   8.   0.]
 [  0.   0.   0.   0.   0.]
 [  0.   0.   0.   0.   0.]
 [ 18.   0.   0.  23.   0.]
 [  8.   3.   0.   0.   0.]]
x coordinates of nonzero elements =  [0 0 3 3 4 4]
y coordinates of nonzero elements =  [0 3 0 3 0 1]
[  8.   8.  18.  23.   8.   3.]
ones filled with nonzero element from rand_normal = 
[[  8.   1.   1.   8.   1.]
 [  1.   1.   1.   1.   1.]
 [  1.   1.   1.   1.   1.]
 [ 18.   1.   1.  23.   1.]
 [  8.   3.   1.   1.   1.]]
Zeros filled with nonzero ele

#### 8
`np.eye` is more generic version of `np.identity` in that both can produce the identity matrix. In fact, `np.identity` does exactly that, however, `np.eye` does so much more, it can place the one on any diagonal besides the main diagnal. see below for example

In [31]:
print('identity matrix from identity function = ',np.identity(5))
print('identity matrix from eye = ',np.eye(5,5))

# But np.eye does so much more
print('place ones 1 diagonal above main diagonal = ', np.eye(5,5,k = 1))
print('place ones 1 diagonal below main diagonal = ', np.eye(5,5,k = -1))
print('place ones 2 diagonals below main diagonal = ', np.eye(5,5,k = -2))

identity matrix from identity function =  [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
identity matrix from eye =  [[ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]]
place ones 1 diagonal above main diagonal =  [[ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]
 [ 0.  0.  0.  0.  1.]
 [ 0.  0.  0.  0.  0.]]
place ones 1 diagonal below main diagonal =  [[ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [ 0.  0.  0.  1.  0.]]
place ones 2 diagonals below main diagonal =  [[ 0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.]]


In [35]:
#9.
idd = np.identity(5)
idd[i,j] = rand_normal[i,j]
print(idd)

[[  8.   0.   0.   8.   0.]
 [  0.   1.   0.   0.   0.]
 [  0.   0.   1.   0.   0.]
 [ 18.   0.   0.  23.   0.]
 [  8.   3.   0.   0.   1.]]


##### 10
`np.arange` creates an array for a specified __step size__, however `np.linspace` creates an array for a specified array length. 

```python
>>> x = np.arange(1,2.5,0.5)
>>> #outputs
>>> array([1,1.5,2])
>>> #whilst
>>>y = np.linspace(1,2,10)
>>>#outputs
>>>array([ 1.        ,  1.11111111,  1.22222222,  1.33333333,  1.44444444,
        1.55555556,  1.66666667,  1.77777778,  1.88888889,  2.        ])
```


### Problem 3
In this part of the excercise, we are going to do a lot of slicing operation. 

1. start of by creating a 6 X 6 matrix of `np.nan`. The `np.nan` data dtype means __Not a Number__. It is typically   used to mean a missing value in data.[Hint: np.full should help you accomplish this task]. 

2. The matrix above can be partitioned into blocks of matrices: top-left, top-right, bottom-left, and bottom-right. All of which are 3 X 3. Now:
    1. Replace top-left with 1
    2. Replace top-right with 2
    3. Replace bottom-left with 3
    4. Replace bottom-right with 4
    
3. Now create a matrix of alphabets like so 

    ```python 
    from string import ascii_lowercase, ascii_uppercase
    ll = list(ascii_lowercase[:9])
    lu = ll = list(ascii_uppercase[:9])
    ll_matrix = np.array(ll,dtype ='|S10').reshape((3,3))
    lu_matrix =  np.array(lu, dtype ='|S10').reshape((3,3))

    ```
   
   1. Take the two matrices ll_matrix and lu_matrix and stack them 
       - Vertically
       - Horizontally
       
       using `np.concatenate`
   2. Accomplish  the _question 2.A_ using `np.vstack` and `np.hstack`
   
   3. View the help documentation for the functions `np.r_` and `np.c_`. What is the difference between the two?
   
   4. Accomplish same task on _question 2.A_ using `np.r_` and `np.c_`
   
   5. In your opinion which of the these methods is more generic? Which method do you prefer?
      
4. Create a 2d array with ones on the border and zeros inside

5. Create an 8 by 8 matrix with  zeros followed by ones in checkerboard fashion. For a 4 X 4 matrix, it looks like so:

|0  | 1 | 0 | 1 |
|---|---|---|---|
| 1 | 0 | 1 | 0 |
|0  | 1 | 0 | 1 |
| 1 | 0 | 1 | 0 |


NOTE: your matrix in part one should look like so:

| `np.nan`| `np.nan` | `np.nan` | `np.nan` | `np.nan` | `np.nan` | 
| --------| ---------| ---------|----------|----------|----------|
| `np.nan`| `np.nan`| `np.nan`| `np.nan`| `np.nan`|`np.nan`|
|`np.nan`|`np.nan`| `np.nan`|`np.nan`|`np.nan`|`np.nan`|
|`np.nan`|`np.nan`|`np.nan`|`np.nan`|`np.nan`|`np.nan`|
|`np.nan`|`np.nan`|`np.nan`|`np.nan`|`np.nan`|`np.nan`|
|`np.nan`|`np.nan`|`np.nan`|`np.nan`|`np.nan`|`np.nan`|


  You should find very helpful factory functions for array creation. You should also find the universal  functions.Read the documentation of a few of them
  .

### Solution for problem 3

In [41]:
#1. 
matr = np.full((6,6), fill_value= np.nan)
print(matr)

#2.A top-left 
matr[:3,:3] = 1
print(matr)

#2.B top-right
matr[:3,3:] = 2
print(matr)

#2.C bottom-left
matr[3:, :3] = 3
print(matr)

#2.D bottom-right
matr[3:,3:] = 4
print(matr)

[[ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]]
[[  1.   1.   1.  nan  nan  nan]
 [  1.   1.   1.  nan  nan  nan]
 [  1.   1.   1.  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]]
[[  1.   1.   1.   2.   2.   2.]
 [  1.   1.   1.   2.   2.   2.]
 [  1.   1.   1.   2.   2.   2.]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]
 [ nan  nan  nan  nan  nan  nan]]
[[  1.   1.   1.   2.   2.   2.]
 [  1.   1.   1.   2.   2.   2.]
 [  1.   1.   1.   2.   2.   2.]
 [  3.   3.   3.  nan  nan  nan]
 [  3.   3.   3.  nan  nan  nan]
 [  3.   3.   3.  nan  nan  nan]]
[[ 1.  1.  1.  2.  2.  2.]
 [ 1.  1.  1.  2.  2.  2.]
 [ 1.  1.  1.  2.  2.  2.]
 [ 3.  3.  3.  4.  4.  4.]
 [ 3.  3.  3.  4.  4.  4.]
 [ 3.  3.  3.  4.  4.  4.]]


In [50]:
#3
from string import ascii_lowercase, ascii_uppercase
ll = list(ascii_lowercase[:9])
lu = list(ascii_uppercase[:9])
ll_matrix = np.array(ll,dtype ='|S10').reshape((3,3))
lu_matrix =  np.array(lu, dtype ='|S10').reshape((3,3))

#3.A
#vertical stacking
v_stack = np.concatenate((ll_matrix,lu_matrix))
print(v_stack)

#Horizontal stacking. 
h_stack = np.concatenate((ll_matrix, lu_matrix), axis = 1)
print(h_stack)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']
 ['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
[['a' 'b' 'c' 'A' 'B' 'C']
 ['d' 'e' 'f' 'D' 'E' 'F']
 ['g' 'h' 'i' 'G' 'H' 'I']]


In [52]:
#3.B
#Vertical stacking
v_stack =np.vstack((ll_matrix,lu_matrix))
print(v_stack)

# horizontal stacking
h_stack = np.hstack((ll_matrix,lu_matrix))
print(h_stack)

[['a' 'b' 'c']
 ['d' 'e' 'f']
 ['g' 'h' 'i']
 ['A' 'B' 'C']
 ['D' 'E' 'F']
 ['G' 'H' 'I']]
[['a' 'b' 'c' 'A' 'B' 'C']
 ['d' 'e' 'f' 'D' 'E' 'F']
 ['g' 'h' 'i' 'G' 'H' 'I']]


#3.
both `np.r_` and `np.c_` tend to have similar behaviour as in, they both expand their inputs if a slicing operation is used but in a row-wise and column-wise respectively: like so 

In [59]:
# act likes np.arange
print('act like np.array(1,2,0.5) = ', np.r_[1:2:0.5])
#acts like np.linspace
print('acts like np.linspace(1,2,10) = ',np.r_[1:2:10j])

# the object types can be converted to a matrix with the `r` and `c`:
a = np.r_[1:2:0.5]
print(type(a))

a_matrix = np.r_['r',1:2:0.5]
print(type(a_matrix))


act like np.array(1,2,0.5) =  [ 1.   1.5]
acts like np.linspace(1,2,10) =  [ 1.          1.11111111  1.22222222  1.33333333  1.44444444  1.55555556
  1.66666667  1.77777778  1.88888889  2.        ]
<type 'numpy.ndarray'>
<class 'numpy.matrixlib.defmatrix.matrix'>


In [62]:
# When a comma separated objects of compatible dimenstions are passed, they get concatenated
ones = np.full((2,2), fill_value = 1)
twos = np.full((2,3), fill_value = 2)
print(np.c_[ones,twos])

# np.r_[ones,twos] won't work because the dimension are not compatible

[[1 1 2 2 2]
 [1 1 2 2 2]]


In [63]:
### specifying  a string integer specifies the which dimension to concatenate a comma separated inputs
#along dimension 0, that is row-wise
ones = np.full((2,2), fill_value = 1)
twos = np.full((2,2), fill_value = 2)
np.r_['0', ones,twos]


array([[1, 1],
       [1, 1],
       [2, 2],
       [2, 2]])

In [65]:
#along dimension 1, that is column-wise
ones = np.full((2,2), fill_value = 1)
twos = np.full((2,2), fill_value = 2)
np.r_['1', ones,twos]

array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

In [66]:
# a string two comma separated integers like '0,2' means concatenate along axis 0 but place the values in an 
# object of at least dimension 2, i.e dim >= 2
ones = np.full((2,2), fill_value = 1)
twos = np.full((2,2), fill_value = 2)
np.r_['1,2', ones,twos]


array([[1, 1, 2, 2],
       [1, 1, 2, 2]])

### Problem 4
###### Basic Operations and ufuncs
Universal functions (ufuncs) are vectorized functions that operate element-wise on an array. Alright lets, take them for a spin

1. Invoke help on `np.core`:

    Type this in the jupyter notebook or the IPython console and the hit the ENTER key. You should find very helpful factory functions for array creation and also the universal functions:
   
     ```python
   
    np.core?

    OR
    
    help(np.core)
     ```
     
2. ###### Normalizing a matrix 
    Consider
    
    ```python
    np.random.seed(1235)
    X = np.floor(np.random.random( size= 25)*100)
    ```
    1. Change the shape to 5X5 matrix and save it in a variable called **`Y`**.
    2. find the range of **`Y`** and store it in variable called **`drange`**. [Hint, range = maximum - minimum]
    3. Deflate Y by the its minimum and store it to a variable called **`Y_deflated`**
    4. divide **`Y_deflated`** by the **`drange`** and store to **`Y_scaled`**

3.

   1. Create two 1-D normal random variables **`X`** and **`Y`** of size 1000
   2. compute their correlation and store to **`corr`** [Hint: np.corrcoef. This gives a matrix of correlation coefficient]. The                correlation coefficient should be on the off diagonal
   3. Now, let compute this manually.
         1. Compute the mean of **`X`** and **`Y`** and store in **`xmean`** and **`ymean`** respectively.
         2. Demean **`X`** and **`Y`** and store the results in **`devx`** and **`devy`**.
         3. Do element-wise multiplication of **`devx`** and **`devy`** and sum the results of the multiplication.             Further divide the results of the sum by total element in **`X`**. Store the results to **`cov`**
         4. Divide results 3.c by **`stdxy`** 
         
         ```python
         stdxy = np.std(X)*np.std(Y)
         ```
         Note: the result must be the same as the one in  _question 3.B_
         


### Solution for problem 4

In [69]:
np.random.seed(1235)
X = np.floor(np.random.random( size= 25)*100)

#2.A
Y = X.reshape((5,5))

#2.B
drange = np.max(Y) - np.min(Y)

#2.C
Y_deflated = Y - np.min(Y)

#2.D
Y_scaled = Y_deflated/drange

print('Y = ', Y)
print('scaled Y = ', Y_scaled)



Y =  [[ 95.  99.  47.  94.  74.]
 [ 83.  24.  36.  37.  65.]
 [ 71.  77.  45.  93.  95.]
 [ 22.  44.  17.  81.  80.]
 [ 63.  74.  92.  17.  81.]]
scaled Y =  [[ 0.95121951  1.          0.36585366  0.93902439  0.69512195]
 [ 0.80487805  0.08536585  0.23170732  0.24390244  0.58536585]
 [ 0.65853659  0.73170732  0.34146341  0.92682927  0.95121951]
 [ 0.06097561  0.32926829  0.          0.7804878   0.76829268]
 [ 0.56097561  0.69512195  0.91463415  0.          0.7804878 ]]


In [82]:
#3.
np.random.seed(1234567)
X = np.random.standard_normal(1000)
Y = np.random.standard_normal(1000)

temp = np.corrcoef(X,Y)
corr = temp[0,1]
print('Correlation coefficient = ', corr)


# Computing it manually

xmean = np.mean(X)
ymean = np.mean(Y)

devx = X - xmean
devy = Y - ymean

cov = sum(devx*devy)/len(X)

stdxy = np.std(X)*np.std(Y)

man_corr = cov/stdxy

print('Manually calculated correlation coefficient = ', man_corr)

Correlation coefficient =  -0.0271945987383
Manually calculated correlation coefficient =  -0.0271945987383


### Problem 5

The code below loads data from a file or (file-like) object.

In this part, we are going to explore various options of loading data using numpy


### Demo

#### Your turn to try


```python
data = """
 #This comment
 #Okay so I'm adding another comment here
 #I guess it doesn't hurt to add more
 Value1,  Value2,  Value3\n
 0.2536,  0.1008,  0.3857\n
 0.4839,  0.4536,  0.3561\n
 0.1292 , 0.6875,  0.5929\n
 0.1781,  0.3049,  0.8928\n
 0.6253,  0.3486,  0.8791
 #extra info down here
"""
```

1. Visit [Help](https://docs.scipy.org/doc/numpy-dev/user/basics.io.genfromtxt.html#defining-the-input). This page will aid you to complete this task

2. Load the data into a matrix form( we shall do it using two approaches):
    - Using skip_header and skip_footer
    - Using comment
    - data type should be np.float32

3. compute the mean and standard deviation of each columns. [Hint: use the random module]

4. Demean each columns with their respective mean.

5. Scale the results of _question 4_  to standardise each column.

### Solution for problem 5

In [111]:
from io import BytesIO

data = """
 #This comment
 #Okay so I'm adding another comment here
 #I guess it doesn't hurt to add more
 #Value1,  Value2,  Value3\n
 0.2536,  0.1008,  0.3857\n
 0.4839,  0.4536,  0.3561\n
 0.1292 , 0.6875,  0.5929\n
 0.1781,  0.3049,  0.8928\n
 0.6253,  0.3486,  0.8791
 #extra info down here
"""
byte_data = BytesIO(data)

# # approach one
data = np.genfromtxt(byte_data,
                    delimiter = ",",
                    skip_header = 4,
                     dtype = np.float32,
                     names = ['Value1', 'Value2', 'Value3']
                    )
data = np.array([data[i] for i in data.dtype.names]).T
print(data)

## approach two: the easiers

# data = np.genfromtxt(byte_data,
#                     delimiter = ",",
#                      comments = "#",
#                      dtype = np.float32
#                     )



[[ 0.2536      0.1008      0.38569999]
 [ 0.48390001  0.45359999  0.35609999]
 [ 0.1292      0.6875      0.59289998]
 [ 0.1781      0.30489999  0.89279997]
 [ 0.62529999  0.3486      0.87910002]]


In [114]:
#3.
means = data.mean(axis = 0)
print('means of each column = ', means)

std = data.std(axis = 0)
print('standard deviatio of each column = ', std)

means of each column =  [ 0.33401999  0.37908     0.62132001]
standard deviatio of each column =  [ 0.18975653  0.19211848  0.23100565]


In [116]:
#4. and 5.
demean = data - means

standardized = demean/std

print('demeanded data = ', demean , sep = '\n')
print('standardized data = ', standardized, sep = '\n')

demeanded data = 
[[-0.08041999 -0.27827999 -0.23562002]
 [ 0.14988002  0.07451999 -0.26522002]
 [-0.20481999  0.30842    -0.02842003]
 [-0.15591998 -0.07418001  0.27147996]
 [ 0.29128    -0.03048     0.25778002]]
standardized data = 
[[-0.42380616 -1.44848108 -1.01997519]
 [ 0.78985435  0.3878856  -1.14811051]
 [-1.07938313  1.60536349 -0.12302743]
 [-0.82168442 -0.38611594  1.17520916]
 [ 1.53501964 -0.15865208  1.1159035 ]]
