In [4]:
import numpy as np

## The Basics

Find indices of non zero elements from [1,2,0,0,4,0]

In [5]:
x = np.array([1,2,0,0,4,0])  #Right
# x = np.array(1,2,0,0,4,0)  #wrong

In [6]:
# Create a null vector of size 10, change the third element to 3
x = np.zeros(10)
print x
x[2] = 3
print x

[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
[ 0.  0.  3.  0.  0.  0.  0.  0.  0.  0.]


In [7]:
# Create a vector starting at 12 and going to 17
vector = np.arange(12,18)
vector

array([12, 13, 14, 15, 16, 17])

In [8]:
# Create a 3 by 3 matrix with values ranging from 0 to 8
vector = np.arange(0,9)
ans = vector.reshape(3,3)
ans

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [9]:
# Generate a 3 by 3 matrix of standard normal random variables
x = np.random.normal(size = 9)
y = x.reshape(3,3)
y

array([[-0.11807442,  0.65146285,  0.51644735],
       [ 0.5098928 , -0.74055022,  0.0996817 ],
       [ 0.14712601, -1.51620946,  0.21016844]])

In [10]:
# Create a 3 by 3 identity matrix
q = np.eye(3)
q

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [11]:
# Create a 5 by 5 matrix of random numbers and find the minimum and maximum
A = np.random.random(25)
B = A.reshape(5,5)
minN = B.min()
maxN = B.max()
print minN, maxN

0.0556398401346 0.925857861912


In [12]:
# Create a 2d array with ones on the border and zeros inside
A = np.zeros((5,5))
A[0,:] = 1
A[4,:]= 1
A[:,0] = 1
A[:,4] = 1
print A


[[ 1.  1.  1.  1.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  0.  0.  0.  1.]
 [ 1.  1.  1.  1.  1.]]


In [13]:
# Create an 8 by 8 matrix with  zeros followed by ones in 
# checkerboard fashion
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1 # one to end in jumps of two ( in rows ) and begin to end in jumps of two 
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


In [14]:
#  Normalize a 5 by 5 matrix of random integer numbers between 0 and 100
X= np.random.random( size= 25)*100
Y = X.reshape(5,5)
ymin, ymax = Y.min(), Y.max()
Z = (Y-ymin)/(ymax-ymin)
Z


array([[ 0.4145042 ,  0.18531083,  0.42340137,  0.58890055,  1.        ],
       [ 0.43813048,  0.51023155,  0.28426727,  0.56679334,  0.8541037 ],
       [ 0.33394851,  0.36848548,  0.90144521,  0.2375973 ,  0.13527381],
       [ 0.04847739,  0.9726074 ,  0.1775128 ,  0.07479174,  0.102434  ],
       [ 0.64975247,  0.        ,  0.58881656,  0.07732884,  0.48412114]])

In [15]:
# Multiply a 5 by 3 matrix with a 3  by 4 matrix
A = np.ones((5,3))
B = np.random.random((3,4))
AB = np.dot(A,B)
AB

array([[ 1.44734558,  1.84529143,  1.04775006,  1.12777892],
       [ 1.44734558,  1.84529143,  1.04775006,  1.12777892],
       [ 1.44734558,  1.84529143,  1.04775006,  1.12777892],
       [ 1.44734558,  1.84529143,  1.04775006,  1.12777892],
       [ 1.44734558,  1.84529143,  1.04775006,  1.12777892]])

In [16]:
# Create a 5 by 5 matrix with row values ranging from 0 to 4
Z = np.zeros((5,5))
Z = Z + np.arange(5)
Z

array([[ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.],
       [ 0.,  1.,  2.,  3.,  4.]])

In [17]:
# Setup a matrix A of size 3 by 4 with the numbers 7 in each entry
# Setup a matrix B of random numbers as a 3 by 4 matrix
# multiply pointwise the two matrices
# Transpose B to a 4 by 3 matrix and  compute A*B' ( matrix multiplication)


In [32]:
A = np.full((3,4),7.0)
# If you did not know this you could 
A = np.ones((3,4))*7.0
B = np.random.random((3,4))
Bprime = np.transpose(B)
C = A*B
D = np.dot(A, Bprime)


In [34]:
# Create a matrix, eg A above.
# Now add a vector to each row of the matrix
A = np.full((3,4),7.0)
rowv = np.array([1,0,2,0])
C = A*rowv
C

array([[  7.,   0.,  14.,   0.],
       [  7.,   0.,  14.,   0.],
       [  7.,   0.,  14.,   0.]])

In [35]:
# In the above each row of the "big" matrix multiplied pointwise 
# with the one row we specified 

# Now lets see what would happen if we had a big array and  did the 
# same thing with a matrix


In [42]:
A = np.full((20,2),7.0)
B = np.array([[1,0], [0,1]])
# C = A*B
# This will not work because it is not obvious what you are doing!
# But if A is  a column vector of size 4 and B is  a row vector of size 3
# Lets see what happens 
A = np.array([[1],[2],[3],[4]])
B = np.array([1,2,3])
C = A*B
# each element of the column vector is multiplied by each element of the 
# row vector. So we end up with a 4 by 3 matrix
C

array([[ 1,  2,  3],
       [ 2,  4,  6],
       [ 3,  6,  9],
       [ 4,  8, 12]])

In [43]:
vec1=np.array([-1.,4.,-9.])
mat1 = np.array([[ 1., 3., 5.], [7., -9., 2.], [4., 6., 8. ]])
vec2 = (np.pi/4)* vec1
                

Form a 2D array without typing it explicitly with 
[[1,  6, 11],
 [2,  7, 12],
 [3,  8, 13],
 [4,  9, 14],
 [5, 10, 15]]



In [51]:
x = np.arange(1,16)
x = np.reshape(x, (5,3), 'F')
x

array([[ 1,  6, 11],
       [ 2,  7, 12],
       [ 3,  8, 13],
       [ 4,  9, 14],
       [ 5, 10, 15]])

In [52]:
# Now generate a new array containing the second and fourth row

In [58]:
y = np.zeros((2,3))
y[0,:]= x[1,:]
y[1,:] = x[3,:]
y


array([[  2.,   7.,  12.],
       [  4.,   9.,  14.]])

#### To import an image  use the command 
##### img src="Snip1.png",width=300,height=400>


<img src="Snip1.png",width=300,height=400>

In [64]:
# Create an array of ones
np.ones((3,4))

# Create an array of zeros
np.zeros((2,3,4),dtype=np.int16)

# Create an array with random values
np.random.random((2,2))

# Create an empty array
np.empty((3,2))

# Create a full array
np.full((2,2),7)

# Create an array of evenly-spaced values
A1 = np.arange(10,25,5)  # will create 10, 15 and 20

# Create an array of evenly-spaced values
A2 =  np.linspace(0,2,9)  # will divide the interval 2  by 8 to create 9 numbers 
                    # equally spaced with endpoints 0 and 2.
print 'A1=', A1
print 'A2=', A2

A1= [10 15 20]
A2= [ 0.    0.25  0.5   0.75  1.    1.25  1.5   1.75  2.  ]


Loading Numpy Arrays from Text

In [71]:
A = np.full((7,3),3.0)
print(len(A))
print( A.size)
print(A.ndim)
Y = np.transpose(A)
print(len(Y))

7
21
2
3


In [79]:
x = np.ones((6,4))

y = np.random.random((1,4))
z = x+y
z

array([[ 1.03078293,  1.49809096,  1.31425875,  1.27278119],
       [ 1.03078293,  1.49809096,  1.31425875,  1.27278119],
       [ 1.03078293,  1.49809096,  1.31425875,  1.27278119],
       [ 1.03078293,  1.49809096,  1.31425875,  1.27278119],
       [ 1.03078293,  1.49809096,  1.31425875,  1.27278119],
       [ 1.03078293,  1.49809096,  1.31425875,  1.27278119]])